### 1. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10.

In [1]:
import numpy as np

In [26]:
arr1 = np.arange(100,200,10)
arr1

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

### 2. Write a NumPy program to create a 3x3x3 array filled with arbitrary values and find the minimum and maximum values.

In [3]:
arr2 = np.random.randint(0,100, size = (3,3))
arr2

array([[ 0, 75, 99],
       [ 6, 87, 70],
       [98, 53, 77]])

In [4]:
print('Minimum value is: ', np.min(arr2))
print('Maximum value is: ', np.max(arr2))

Minimum value is:  0
Maximum value is:  99


### 3. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [5]:
arr3 = np.diag([1,2,3,4,5])
arr3

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### 4. Given an array
 arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
- i) Extract all odd numbers from arr
- ii) Replace all odd numbers in arr with -1

In [12]:
arr4 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
for i in range(len(arr4)):
    if i % 2 != 0:
        print(arr4[i])
        arr4[i] = -1
print(arr4)
        

1
3
5
7
9
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### 5.Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0.

In [8]:
arr_identity = np.identity(3, dtype = int)
arr_identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### 6. Write a NumPy program to convert an array to a float type.

In [9]:
print('An array is: ', arr4)
arr_float = arr4.astype(np.float)
print('Coverted array is:', arr_float)

An array is:  [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Coverted array is: [ 0. -1.  2. -1.  4. -1.  6. -1.  8. -1.]


### 7. Write a NumPy program to generate five random numbers from the normal distribution.

In [10]:
arr_ran = np.random.normal(size = 5)
arr_ran

array([ 0.19845024,  0.25195301, -1.58807851, -0.96405201,  1.10917373])

### 8. Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [16]:
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
print('Sample Array is:\n',sampleArray)

Sample Array is:
 [[34 43 73]
 [82 22 12]
 [53 94 66]]


In [12]:
newColumn = np.array([[10,10,10]])
sampleArray[:,2] = newColumn
print('New array is:\n', sampleArray)

New array is:
 [[34 43 10]
 [82 22 10]
 [53 94 10]]


### 9. Write a NumPy program to compute the multiplication of two given matrices.

In [13]:
arr5 = np.array([[2,4],[3,5]])
arr6 = np.array([[10,20],[30,40]])
arr5*arr6

array([[ 20,  80],
       [ 90, 200]])

In [14]:
# Method 2
result = np.multiply(arr5,arr6)
result

array([[ 20,  80],
       [ 90, 200]])

### 10. Write a NumPy program to create a random vector of size 10 and sort it.

In [20]:
arr7 = np.random.random(10)
arr7

array([0.79881829, 0.41891352, 0.93147817, 0.71849988, 0.02367299,
       0.85540458, 0.8155129 , 0.25902852, 0.76688223, 0.1357689 ])

In [21]:
arr7.sort()
arr7

array([0.02367299, 0.1357689 , 0.25902852, 0.41891352, 0.71849988,
       0.76688223, 0.79881829, 0.8155129 , 0.85540458, 0.93147817])

### 11. Write a NumPy program to compute the covariance matrix of two arrays.

In [29]:
print('Array 1 is: \n', arr1)
arr8 = np.random.randint(0,50,10)
print('Array 2 is: \n', arr8)
cov = np.cov(arr1,arr8)
print('Covariance of two arrays is: \n', cov)

Array 1 is: 
 [100 110 120 130 140 150 160 170 180 190]
Array 2 is: 
 [32 31 16 32 49 14 41 25 42 18]
Covariance of two arrays is: 
 [[916.66666667  -6.66666667]
 [ -6.66666667 139.55555556]]


### 12.Create a 4X2 integer array and Prints its
- i)The shape of an array.
- ii) Array dimensions.
- iii) The Length of each element of the array in bytes


In [32]:
full = np.full((4,2),5)
full

array([[5, 5],
       [5, 5],
       [5, 5],
       [5, 5]])

In [34]:
print('The shape of an array is: ', full.shape)
print('The dimension of an array is: ', full.ndim)
print('The length of each element of an array in bytes is: ', full.itemsize)

The shape of an array is:  (4, 2)
The dimension of an array is:  2
The length of each element of an array in bytes is:  4


### 13. Write a NumPy program to concatenate element-wise two arrays of string

In [4]:
str_arr1 = np.array(['Data'])
str_arr2 = np.array(['Folkz'])
concat = np.char.add(str_arr1,str_arr2)
concat

array(['DataFolkz'], dtype='<U9')

### 14. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.

In [7]:
strarr = np.char.capitalize(['numpy'])
strarr

array(['Numpy'], dtype='<U5')

In [11]:
print(np.char.lower(strarr))
print(np.char.upper(strarr))
print(np.char.swapcase(strarr))
print(np.char.title(strarr))

['numpy']
['NUMPY']
['nUMPY']
['Numpy']


### 15. Write a NumPy program to convert a given array into a list

In [14]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
list(arr4)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### 16. Write a NumPy program to compute the sum of all elements, sum of each column and sum of each row of a given array.

In [17]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [19]:
print('Sum of all elements:', np.sum(sampleArray))

Sum of all elements: 479


In [23]:
sumcol0 = np.sum(sampleArray[:,0])
sumcol1 = np.sum(sampleArray[:,1])
sumcol2 = np.sum(sampleArray[:,2])
print('Sum of column 0:', sumcol0,'Sum of column 1:',sumcol1 ,'Sum of column 2:',sumcol2)

Sum of each column 1: 169 Sum of each column 1: 159 Sum of each column 1: 151


In [25]:
sumrow0 = np.sum(sampleArray[:1])
sumrow1 = np.sum(sampleArray[1:2])
sumrow2 = np.sum(sampleArray[2])
print('Sum of row 0:', sumrow0,'Sum of row 1:',sumrow1 ,'Sum of row 2:',sumrow2)

Sum of row 0: 150 Sum of row 1: 116 Sum of row 2: 213


### 17. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [32]:
arr9 = np.random.rand(10,4)
arr9

array([[0.22765213, 0.04971711, 0.13141026, 0.65963046],
       [0.95795953, 0.74373275, 0.99913092, 0.046753  ],
       [0.91542188, 0.51644947, 0.78849401, 0.02978595],
       [0.53592369, 0.43473278, 0.51777015, 0.24867583],
       [0.3085435 , 0.86530629, 0.95482266, 0.14352653],
       [0.06852103, 0.16592989, 0.19036938, 0.1088876 ],
       [0.4807407 , 0.03464742, 0.97462918, 0.52622501],
       [0.71928334, 0.89668473, 0.70713225, 0.63588986],
       [0.57745385, 0.36185676, 0.07784286, 0.94255387],
       [0.60500049, 0.97362384, 0.95786699, 0.99988448]])

In [34]:
var = arr9[0:5]
var

array([[0.22765213, 0.04971711, 0.13141026, 0.65963046],
       [0.95795953, 0.74373275, 0.99913092, 0.046753  ],
       [0.91542188, 0.51644947, 0.78849401, 0.02978595],
       [0.53592369, 0.43473278, 0.51777015, 0.24867583],
       [0.3085435 , 0.86530629, 0.95482266, 0.14352653]])

### 18. Write a NumPy program to get the unique elements of a 1D and 2D array.

In [50]:
arr10 = np.array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
arr10[1] = np.array([[1,5,3,9,4]])
arr10

array([[0, 1, 2, 3, 4],
       [1, 5, 3, 9, 4]])

In [51]:
uni2D = np.unique(arr10)
uni2D

array([0, 1, 2, 3, 4, 5, 9])

In [39]:
arr

array([-10.  ,  12.  ,   0.12,  -0.2 ,  12.  ])

In [38]:
uni1D = np.unique(arr)
uni1D

array([-10.  ,  -0.2 ,   0.12,  12.  ])

### 19. Write a NumPy program to get the unique elements of an array.
 arr= [ -10 12.12 -0.2]

In [29]:
arr = np.array([-10, 12,.12,-0.2,12])
print(arr)
np.unique(arr)

[-10.    12.     0.12  -0.2   12.  ]


array([-10.  ,  -0.2 ,   0.12,  12.  ])

### 20. Write a NumPy program to save a given array to a text file and load it. You have to save and load files using numpy library .

In [55]:
arr11 = np.arange(16).reshape(4, 4)
print("Original array:\n",arr11)
np.savetxt('temp.txt', arr11) 
result = np.loadtxt('temp.txt')
print("After loading, content of the text file is:\n", result)

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After loading, content of the text file is:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
